In [ ]:
###### packages ####                                                      #### 45 th class
******** EDA *******
1)  Pandas : Dataframe analysis
2)  numpy  : Numerical Python/Number python
3)  matplotlib : plot
4)  seaborn :   plot
5)  plotly  :   plot
6)  bokhe   :   plot


********** ML ********
7)   scikit-learn
********** DL ********
8)   tensorflow
9)   keras
10)  pytorch
11)  cv: computer vision
********* NLP ********
12)  NLTK
13)  scipy

$Step-1$

**Import required pcakages**

In [65]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

$Step-2$

**Read the data**

$visadataset$

In [3]:
# file location
# file name 
# extention

file_path="C:\\DS_Py\\Visadataset.csv"

pd.read_csv(file_path)

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

$Bankdata$

In [54]:
file_path="C:\\DS_Py\\bank.csv"
                                      # some times it include some random data sets in 1 column ,,, during that time use ""sep=';'
pd.read_csv(file_path)
# pd.read_csv(file_path,sep=';')          # ulta is comming becz dataset is correct formate

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,unknown,yes
45207,71,retired,divorced,primary,no,1729,no,no,cellular,17,nov,456,2,-1,0,unknown,yes
45208,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,184,3,success,yes
45209,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,-1,0,unknown,no
45210,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,nov,361,2,188,11,other,no

$Step-3$

**Create a dataframe using lists**

In [13]:
list1=['Ram','Raheem','Robert']
list2=[30,31,32]

pd.DataFrame(zip(list1,list2))

        0   1
0     Ram  30
1  Raheem  31
2  Robert  32

In [20]:
list1=['Ram','Raheem','Robert']
list2=[30,31,32]
cols=['Name','Age']
names=pd.DataFrame(zip(list1,list2),columns=cols)

$step - 4$

**How to save the dataframe in local**

In [21]:
# whatis your datd fram name : names
# where you want to save: "C:\\DS_Py\\"
# what name you want to provide : NAMES

names.to_csv("C:\\DS_Py\\NAMES.csv")

In [55]:
# our python file and data file are in the same location , no need to give full path
# if both files are in different location , we have to give full path 


# this will save in the python files
names.to_csv("NAMES.csv")

In [29]:
# it will not create extra column as index 

names.to_csv("NAMES1.csv",index=False)

$Task - 1$

**Read NAMES and NAMES1**

In [36]:
file_name="NAMES.csv"

pd.read_csv(file_name)

# how can we avoid nunamed:0

   Unnamed: 0    Name  Age
0           0     Ram   30
1           1  Raheem   31
2           2  Robert   32

In [37]:
file_name="NAMES1.csv"

pd.read_csv(file_name)

     Name  Age
0     Ram   30
1  Raheem   31
2  Robert   32

$step - 5$

**Add a new column to existing dataframe**

In [61]:
# What is your data frame name: names
# What is the name of the column you want add : city
# how many rows we have in original data : 3
# what is your new data = ['Hyb','chennai','Blr']

names['city']=['Hyb','chennai','Blr']
names


# no fo city should meet the == original data length==3,  if cities ==4 or ==2 it will give error

     Name  Age     city
0     Ram   30      Hyb
1  Raheem   31  chennai
2  Robert   32      Blr

$Step - 6$

**How to Drop the column**

In [62]:
# Data frame name: name

# axis=1 ======== columns
# axis=0 ======== rows


# ame of the column = city 


# inplace=True: data will be overwrite

In [64]:
names.drop('city',axis=1,inplace=True)
names

     Name  Age
0     Ram   30
1  Raheem   31
2  Robert   32

- How to read csv data                                                                       # 46 th class

- How to create the  dataframe using List

- How to save in local

- How to add the column

- How to drop the column

$Dataframe-using-dictionary$

In [79]:
dict={'Students':['Ram','Raheem','Robert'],
     'Age':[30,31,32]}
dict
pd.DataFrame(dict)

# length of the names and age should be same

  Students  Age
0      Ram   30
1   Raheem   31
2   Robert   32

In [73]:
pd.DataFrame(dict,columns=['A','B']) # conclusion : it will not work

Empty DataFrame
Columns: [A, B]
Index: []

In [74]:
pd.DataFrame(dict,index=['A','B','C'])

    Names  Age
A     Ram   30
B  Raheem   31
C  Robert   32

In [77]:
names

     Name  Age
0     Ram   30
1  Raheem   31
2  Robert   32