$Step - 1$

**Import required packages**

In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

$Step - 2$

**read the dataset**

In [29]:
file_path="C:\\DS_Py\\Visadataset.csv"
visa_df=pd.read_csv(file_path)
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

$Shape$

In [5]:
# dataframe name is visa_df
visa_df.shape

(25480, 12)

In [6]:
type(visa_df)

pandas.core.frame.DataFrame

In [8]:
print('the number of rows are:',visa_df.shape[0])
print('the number of columns are:',visa_df.shape[1])

the number of rows are: 25480
the number of columns are: 12

In [ ]:
# <package_name>.<method_name>()

In [9]:
visa_df.shape()

TypeError: 'tuple' object is not callable

- Function are used to call
- Function means()
- not callable means, remove the brackets

$Size$

In [11]:
visa_df.size

# number of rows*number of columns

305760

In [12]:
visa_df.shape[0]*visa_df.shape[1]

# 25480*12

305760

$Columns$

In [13]:
visa_df.columns

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [14]:
type(visa_df.columns)

pandas.core.indexes.base.Index

In [15]:
visa_df.columns.to_list

<bound method IndexOpsMixin.tolist of Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')>

In [16]:
visa_df.columns.to_list()

['case_id',
 'continent',
 'education_of_employee',
 'has_job_experience',
 'requires_job_training',
 'no_of_employees',
 'yr_of_estab',
 'region_of_employment',
 'prevailing_wage',
 'unit_of_wage',
 'full_time_position',
 'case_status']

- when it shows " not callable" , don't use bracket()
- if output shows Bound method use "Bracket()"

In [ ]:
dict() ======== to_dict
list() ======== to_list

$Dtypes$

In [19]:
visa_df.dtypes

# object means catogorical column
# int64 and float64 for numerical column

case_id                   object
continent                 object
education_of_employee     object
has_job_experience        object
requires_job_training     object
no_of_employees            int64
yr_of_estab                int64
region_of_employment      object
prevailing_wage          float64
unit_of_wage              object
full_time_position        object
case_status               object
dtype: object

In [18]:
type(visa_df.dtypes)

pandas.core.series.Series

In [21]:
visa_df.dtypes.index       # left side data you will get

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [23]:
visa_df.dtypes.keys()

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [34]:
visa_df.dtypes.values  # if we use "brackets ()" it showing error == not callable, so not to use "()"

array([dtype('O'), dtype('O'), dtype('O'), dtype('O'), dtype('O'),
       dtype('int64'), dtype('int64'), dtype('O'), dtype('float64'),
       dtype('O'), dtype('O'), dtype('O')], dtype=object)

In [33]:
type(visa_df.dtypes.values) 

# numpy n dimensions array

numpy.ndarray

In [29]:
# important**************************************************************


dir(visa_df.dtypes)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__bool__',
 '__class__',
 '__column_consortium_standard__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__firstlineno__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_as_manager',
 '_attrs',
 '_binop',
 '_can_hold_na',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_expanddim_from_mgr',
 '_constructor_from_mgr',
 '_data',
 '_deprecate_downcast',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_duplicated',
 '_find_valid_index',
 '_flags',
 '_flex_method',
 '_from_mgr',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cacher',
 '_get_cleaned_column_resolvers',
 '_get_index_resolvers',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_rows_with_mask',
 '_get_value',
 '_get_values_tuple',
 '_get_with',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_init_dict',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_cached',
 '_is_copy',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_is_view_after_cow_rules',
 '_item_cache',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_map_values',
 '_maybe_update_cacher',
 '_memory_usage',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_name',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_protect_consolidate',
 '_reduce',
 '_references',
 '_reindex_axes',
 '_reindex_indexer',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_single',
 '_repr_data_resource_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_set_as_cached',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_labels',
 '_set_name',
 '_set_value',
 '_set_values',
 '_set_with',
 '_set_with_engine',
 '_shift_with_freq',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'argmax',
 'argmin',
 'argsort',
 'array',
 'asfreq',
 'asof',
 'astype',
 'at',
 'at_time',
 'attrs',
 'autocorr',
 'axes',
 'backfill',
 'between',
 'between_time',
 'bfill',
 'bool',
 'case_id',
 'case_status',
 'case_when',
 'clip',
 'combine',
 'combine_first',
 'compare',
 'continent',
 'convert_dtypes',
 'copy',
 'corr',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'divmod',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtype',
 'dtypes',
 'duplicated',
 'education_of_employee',
 'empty',
 'eq',
 'equals',
 'ewm',
 'expanding',
 'explode',
 'factorize',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'full_time_position',
 'ge',
 'get',
 'groupby',
 'gt',
 'has_job_experience',
 'hasnans',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'interpolate',
 'is_monotonic_decreasing',
 'is_monotonic_increasing',
 'is_unique',
 'isin',
 'isna',
 'isnull',
 'item',
 'items',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'list',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'memory_usage',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'name',
 'nbytes',
 'ndim',
 'ne',
 'nlargest',
 'no_of_employees',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'plot',
 'pop',
 'pow',
 'prevailing_wage',
 'prod',
 'product',
 'quantile',
 'radd',
 'rank',
 'ravel',
 'rdiv',
 'rdivmod',
 'region_of_employment',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'repeat',
 'replace',
 'requires_job_training',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'searchsorted',
 'sem',
 'set_axis',
 'set_flags',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'std',
 'str',
 'struct',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_frame',
 'to_hdf',
 'to_json',
 'to_latex',
 'to_list',
 'to_markdown',
 'to_numpy',
 'to_period',
 'to_pickle',
 'to_sql',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unique',
 'unit_of_wage',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'view',
 'where',
 'xs',
 'yr_of_estab']

In [36]:
list1=[1,2,3]
list1

[1,2,3]+[4,5,6]

[1, 2, 3, 4, 5, 6]

In [38]:
np.array([1,2,3])+np.array([4,5,6])

array([5, 7, 9])

- array[] ====> numpy
- index[] ====> pandas index
- pandas.datafram
- pandas.series

$task-1$

**seperate categorical columns, numerical column in list**

In [45]:
visa_df.dtypes

# to do this into list convert it into dictionary

case_id                   object
continent                 object
education_of_employee     object
has_job_experience        object
requires_job_training     object
no_of_employees            int64
yr_of_estab                int64
region_of_employment      object
prevailing_wage          float64
unit_of_wage              object
full_time_position        object
case_status               object
dtype: object

In [48]:
dict(visa_df.dtypes)

{'case_id': dtype('O'),
 'continent': dtype('O'),
 'education_of_employee': dtype('O'),
 'has_job_experience': dtype('O'),
 'requires_job_training': dtype('O'),
 'no_of_employees': dtype('int64'),
 'yr_of_estab': dtype('int64'),
 'region_of_employment': dtype('O'),
 'prevailing_wage': dtype('float64'),
 'unit_of_wage': dtype('O'),
 'full_time_position': dtype('O'),
 'case_status': dtype('O')}

In [63]:
dict1=dict(visa_df.dtypes)
for i,j in dict1.items():
    if j=='object':
        print(i)

cat=[key for key,value in dict1.items() if value=='object']
cat

case_id
continent
education_of_employee
has_job_experience
requires_job_training
region_of_employment
unit_of_wage
full_time_position
case_status

['case_id',
 'continent',
 'education_of_employee',
 'has_job_experience',
 'requires_job_training',
 'region_of_employment',
 'unit_of_wage',
 'full_time_position',
 'case_status']

$Head$

In [66]:
visa_df.head()  # top 5 rows

# starting with index 0

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified

In [68]:
visa_df.head(10)

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
5,EZYV06,Asia,Master's,Y,N,2339,2012,South,78252.1400,Year,Y,Certified
6,EZYV07,Asia,Bachelor's,N,N,4985,1994,South,53635.3900,Year,Y,Certified
7,EZYV08,North America,Bachelor's,Y,N,3035,1924,West,418.2298,Hour,Y,Denied
8,EZYV09,Asia,Bachelor's,N,N,4810,2012,Midwest,74362.1900,Year,Y,Certified
9,EZYV10,Europe,Doctorate,Y,N,2251,1995,South,67514.7600,Year,Y,Certified

$tail$

In [72]:
visa_df.tail()   # last 5 rows

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.57,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.79,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.85,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.77,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.91,Year,Y,Certified

$take$

In [76]:
list1=[100,200,300]
visa_df.take(list1)      # it will give which coulmns number u want

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
100,EZYV101,Asia,Master's,Y,N,2227,2007,Northeast,28243.79,Year,Y,Certified
200,EZYV201,Asia,Doctorate,Y,N,3282,1979,West,74441.11,Year,Y,Certified
300,EZYV301,Asia,Master's,Y,N,3268,2012,Midwest,101371.21,Year,Y,Certified

In [78]:
list1=[100,200,300]
visa_df.take(list1,axis=1)

# axis=1 column
# 100 200 300

IndexError: indices are out-of-bounds

In [30]:
visa_df.take([2,5,11],axis=1)

# if you give 12 insted of 11 == error ,becz max columns == 11

      education_of_employee  no_of_employees case_status
0               High School            14513      Denied
1                  Master's             2412   Certified
2                Bachelor's            44444      Denied
3                Bachelor's               98      Denied
4                  Master's             1082   Certified
...                     ...              ...         ...
25475            Bachelor's             2601   Certified
25476           High School             3274   Certified
25477              Master's             1121   Certified
25478              Master's             1918   Certified
25479            Bachelor's             3195   Certified

[25480 rows x 3 columns]

In [86]:
visa_df.take([2,5,11],axis=0)

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.86,Year,Y,Denied
5,EZYV06,Asia,Master's,Y,N,2339,2012,South,78252.14,Year,Y,Certified
11,EZYV12,Asia,High School,Y,N,4069,2005,Northeast,70813.09,Year,Y,Denied

$task - 2$

**I want 150 300,450 rows from 5,8,12**

In [90]:
visa_df.take([4,7,11],axis=1)

      requires_job_training region_of_employment case_status
0                         N                 West      Denied
1                         N            Northeast   Certified
2                         Y                 West      Denied
3                         N                 West      Denied
4                         N                South   Certified
...                     ...                  ...         ...
25475                     Y                South   Certified
25476                     N            Northeast   Certified
25477                     N                South   Certified
25478                     Y                 West   Certified
25479                     N              Midwest   Certified

[25480 rows x 3 columns]

In [36]:
visa_df.take([4,7,11],axis=1).take([150,300,450])

    requires_job_training region_of_employment case_status
150                     N                 West      Denied
300                     N              Midwest   Certified
450                     Y                 West      Denied

In [31]:
visa_df.take([100:200])

SyntaxError: invalid syntax (1887675126.py, line 1)

$ iloc$ - $loc$

In [ ]:
visa_df.iloc[<rows>,<columns>]
visa_df.iloc[start:end,start:end]

In [96]:
visa_df.iloc[100:150]                  # all the columns

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
100,EZYV101,Asia,Master's,Y,N,2227,2007,Northeast,28243.7900,Year,Y,Certified
101,EZYV102,Asia,Master's,Y,N,334,2007,Midwest,43421.8800,Year,Y,Certified
102,EZYV103,Asia,Bachelor's,Y,N,224,2008,Midwest,80253.7800,Year,Y,Certified
103,EZYV104,Asia,Doctorate,Y,N,367,1982,West,115235.9500,Year,Y,Certified
104,EZYV105,Asia,Master's,Y,N,306,2003,Northeast,95200.8600,Year,N,Certified
105,EZYV106,North America,Doctorate,Y,N,2317,1995,Island,41613.5200,Year,Y,Certified
106,EZYV107,Asia,Bachelor's,N,N,890,1981,West,64137.4100,Year,Y,Denied
107,EZYV108,Asia,Bachelor's,Y,N,2002,2006,South,66295.4300,Year,Y,Certified
108,EZYV109,Asia,Bachelor's,N,N,2903,1943,Midwest,97520.0200,Year,Y,Certified
109,EZYV110,Asia,Bachelor's,Y,N,2504,2001,West,65164.5700,Year,Y,Certified
110,EZYV111,North America,High School,Y,N,951,1956,Midwest,73957.1700,Year,N,Certified
111,EZYV112,Asia,Master's,Y,N,1327,1864,West,71415.4300,Year,Y,Certified
112,EZYV113,Asia,Bachelor's,Y,N,2421,1974,South,87336.5300,Year,Y,Certified
113,EZYV114,North America,High School,Y,N,1019,2005,South,98966.7200,Week,Y,Certified
114,EZYV115,Asia,Doctorate,N,N,1048,1985,Midwest,83503.6000,Year,Y,Certified
115,EZYV116,Asia,Master's,N,N,3323,2005,Midwest,57590.6600,Year,Y,Certified
116,EZYV117,Asia,Bachelor's,Y,N,509,1997,South,32400.2000,Week,Y,Certified
117,EZYV118,North America,Master's,Y,Y,2225,1976,Northeast,65993.2100,Year,Y,Certified
118,EZYV119,Asia,Bachelor's,Y,N,1641,1984,Midwest,32161.6000,Year,Y,Certified
119,EZYV120,Asia,Master's,N,N,1144,2001,Northeast,16421.3700,Year,Y,Denied
120,EZYV121,North America,Master's,N,N,2334,1971,South,160676.3900,Year,N,Certified
121,EZYV122,South America,Bachelor's,N,N,1415,1913,Northeast,53114.0200,Year,Y,Denied
122,EZYV123,Asia,Doctorate,Y,Y,2754,1997,South,19176.2100,Year,Y,Certified
123,EZYV124,North America,Master's,N,N,1099,2005,West,204832.5200,Year,N,Denied
124,EZYV125,Asia,Master's,Y,N,960,2012,Northeast,40256.0300,Year,Y,Certified
125,EZYV126,North America,Master's,Y,N,2750,1997,West,38841.4400,Year,Y,Certified
126,EZYV127,Asia,High School,Y,N,2753,2010,Northeast,133052.8400,Year,Y,Denied
127,EZYV128,North America,Bachelor's,Y,N,23287,2007,South,75234.6400,Year,N,Certified
128,EZYV129,Asia,Bachelor's,N,N,2140,1997,South,37032.8300,Year,Y,Certified
129,EZYV130,Asia,Bachelor's,N,N,4499,2008,Northeast,61617.7300,Year,Y,Denied
130,EZYV131,South America,High School,N,N,2554,2005,Midwest,247393.0100,Year,Y,Certified
131,EZYV132,Asia,Bachelor's,Y,N,1333,1969,Northeast,341.0229,Hour,Y,Certified
132,EZYV133,Asia,Doctorate,N,N,928,1818,South,30570.9500,Year,Y,Certified
133,EZYV134,Asia,Doctorate,Y,N,4289,2005,Midwest,19477.1000,Year,Y,Certified
134,EZYV135,Asia,Doctorate,Y,Y,113282,2011,Midwest,164893.0000,Year,Y,Certified
135,EZYV136,Asia,Master's,Y,N,1948,2002,South,131584.5000,Year,Y,Certified
136,EZYV137,Asia,Master's,Y,N,1933,1839,Northeast,63896.3500,Year,Y,Certified
137,EZYV138,Asia,Master's,N,N,2847,2013,Midwest,77883.2200,Year,Y,Certified
138,EZYV139,Asia,Bachelor's,Y,N,1195,1914,Midwest,108519.1400,Year,Y,Certified
139,EZYV140,Asia,Master's,Y,N,54,1988,South,47002.5300,Year,N,Certified
140,EZYV141,Asia,Master's,N,N,4390,1944,South,88720.2900,Year,N,Certified
141,EZYV142,Asia,Master's,Y,N,73909,2004,Midwest,60821.7500,Year,Y,Certified
142,EZYV143,Asia,Master's,N,Y,545,1855,South,66324.6900,Year,Y,Certified
143,EZYV144,Asia,Doctorate,Y,N,2831,1977,South,100398.5800,Year,Y,Certified
144,EZYV145,Asia,Bachelor's,N,Y,1634,1999,South,51282.7500,Year,Y,Certified
145,EZYV146,Europe,Bachelor's,Y,N,1810,1943,South,13322.7200,Year,Y,Certified
146,EZYV147,Europe,Bachelor's,Y,N,3290,2005,Northeast,357.8194,Hour,Y,Certified
147,EZYV148,Asia,Master's,Y,N,472,2004,West,4787.4300,Year,Y,Certified
148,EZYV149,Asia,Bachelor's,Y,N,4273,1884,Midwest,149023.9200,Year,Y,Certified
149,EZYV150,Asia,Master's,N,N,2326,1933,West,123739.4100,Year,Y,Denied

In [98]:
visa_df.iloc[50:55,2:6] visa_df.iloc[50:55,2:6]       # visa_df.iloc[start:end,start:end]

# 50 rows 54
# 2 to 5

,education_of_employee,has_job_experience,requires_job_training,no_of_employees
50,Bachelor's,N,N,746
51,Master's,Y,N,3129
52,Bachelor's,N,N,1647
53,High School,Y,N,2438
54,Master's,Y,N,11733

In [99]:
visa_df.iloc[[100,150,200]]

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
100,EZYV101,Asia,Master's,Y,N,2227,2007,Northeast,28243.7900,Year,Y,Certified
150,EZYV151,Asia,Bachelor's,N,N,50351,1975,West,529.1105,Hour,Y,Denied
200,EZYV201,Asia,Doctorate,Y,N,3282,1979,West,74441.1100,Year,Y,Certified

In [101]:
visa_df.iloc[[100,150,200],[5,8,11]]

     no_of_employees  prevailing_wage case_status
100             2227       28243.7900   Certified
150            50351         529.1105      Denied
200             3282       74441.1100   Certified

In [32]:
# 100,200,300  from only case status column

visa_df.iloc[[100,150,200] ,11]          # for large number of columns we cannot count so . if we give "case status" itS won't work


visa_df.iloc[[100,150,200] ,'case_status']  # it is easy but it will take only numbers
#  becz iloc will take only numbers

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [37]:
# To avoid this drawbcak we go for ILOC

visa_df.loc[[100,150,200] ,['case_status']]

    case_status
100   Certified
150      Denied
200   Certified

In [112]:
rows=[100,200,300]
cols=['continent','case_status']
visa_df.loc[rows,cols]

    continent case_status
100      Asia   Certified
200      Asia   Certified
300      Asia   Certified

In [113]:
len(visa_df)

25480

$isnull$

- any missing values are there in the data
- is null you are asking question to computer:True/False
- If any missing values are there it is True
- If data presents/no missing values False

In [114]:
visa_df.isnull()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,False,False,False,False,False,False,False,False,False,False,False,False
25476,False,False,False,False,False,False,False,False,False,False,False,False
25477,False,False,False,False,False,False,False,False,False,False,False,False
25478,False,False,False,False,False,False,False,False,False,False,False,False
25479,False,False,False,False,False,False,False,False,False,False,False,False

In [115]:
visa_df.isnull().sum()

case_id                  0
continent                0
education_of_employee    0
has_job_experience       0
requires_job_training    0
no_of_employees          0
yr_of_estab              0
region_of_employment     0
prevailing_wage          0
unit_of_wage             0
full_time_position       0
case_status              0
dtype: int64

$infO$

In [118]:
visa_df.info()     # what task and methods we did untill here , ""info"" is every thing is in one

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25480 entries, 0 to 25479
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   case_id                25480 non-null  object
 1   continent              25480 non-null  object
 2   education_of_employee  25480 non-null  object
 3   has_job_experience     25480 non-null  object
 4   requires_job_training  25480 non-null  object
 5   no_of_employees        25480 non-null  int64
 6   yr_of_estab            25480 non-null  int64
 7   region_of_employment   25480 non-null  object
 8   prevailing_wage        25480 non-null  float64
 9   unit_of_wage           25480 non-null  object
 10  full_time_position     25480 non-null  object
 11  case_status            25480 non-null  object
dtypes: float64(1), int64(2), object(9)
memory usage: 2.3+ MB

## what we learnt

- shape
- size 
- dtypes
- columns
- we seperated cat and num
- head
- tail
- take
- iloc
- loc
- len
- is null
- info
- take
- iloc
- loc