**Convert Categorical to Numerical data**

In [107]:
# import packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [41]:
file_path="C:\\DS_Py\\Visadataset.csv"
visa_df=pd.read_csv(file_path)
visa_df.head(5)

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified

- In ML algorithems will develop models by using maths
- maths allows only numbers
- so it is very important, you need to pass numerical data only'
- for that we have encoding methods
- Encoding 
    - Label encoder
        - map method
        - np.where
        - LableEncoder package from sklearn

    - one hot encoder
        - pd.get_dummies()

$Method-1:map$

- Read any categorical columns: case_status
- Check how many unique lables are there
- Create a dictionary with those unique lables as keys by providing a number as values

In [42]:
######## read ####################
file_path="C:\\DS_Py\\Visadataset.csv"
visa_df=pd.read_csv(file_path)
visa_df

########### Map ###########
visa_df['case_status'].unique()
dict1={'Certified':0,'Denied':1}
visa_df['case_status'].map(dict1)

# do u want to overwrite existed column
# do you want to create a new column

0        1
1        0
2        1
3        1
4        0
        ..
25475    0
25476    0
25477    0
25478    0
25479    0
Name: case_status, Length: 25480, dtype: int64

**Create a new column**

In [43]:
######## read ####################
file_path="C:\\DS_Py\\Visadataset.csv"
visa_df=pd.read_csv(file_path)
visa_df

########### Map ###########
visa_df['case_status'].unique()
dict1={'Certified':0,'Denied':1}
visa_df['case_status_num']=visa_df['case_status'].map(dict1)
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status,case_status_num
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified,0

**drop case_status_num**

In [44]:
visa_df.drop('case_status_num',axis=1,inplace=True)

In [45]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

**Overwriting the same column(preferable)**

In [48]:
######## read ####################
file_path="C:\\DS_Py\\Visadataset.csv"
visa_df=pd.read_csv(file_path)
visa_df

########### Map ###########
visa_df['case_status'].unique()
dict1={'Certified':0,'Denied':1}
visa_df['case_status']=visa_df['case_status'].map(dict1)
visa_df
# in the map method inplace=True is not there

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [115]:
lables=visa_df['continent'].unique()
num=len(visa_df['continent'].unique())
dict1={}
for i in range(num):
    dict1[lables[i]]=i
print(dict1)    

{lables[i]:i for i in range(num)}

{'Asia': 0, 'Africa': 1, 'North America': 2, 'Europe': 3, 'South America': 4, 'Oceania': 5}

{'Asia': 0,
 'Africa': 1,
 'North America': 2,
 'Europe': 3,
 'South America': 4,
 'Oceania': 5}

$Method-2:np.where$

In [65]:
file_path="C:\\DS_Py\\Visadataset.csv"
visa_df=pd.read_csv(file_path)
visa_df.head(5)

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified

- np.where() is applicable for binary conditions
- which means it is applicable only for two labels
- np.where(condition,Truevalue,Falsee_value)
- for Example: case_status has 2 labels
- Certified==True, Replace certified values with 0
- False value: Replace all denied values with 1

In [66]:
con=visa_df['case_status']=='Certified'
visa_df['case_status']=np.where(con,0,1)

In [67]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

$LabelEncoder$

- LableEncoder is a method from sklearn
- Under sklearn we have sub modules
- One of the submodule: preprocessing
- any sklearn packages we ahve only 3 steps

- step-1: read the package
- step-2: save the package
- step-3: Apply fit transform

In [97]:
file_path="C:\\DS_Py\\Visadataset.csv"
visa_df=pd.read_csv(file_path)
print(visa_df['continent'].head(10))

# step-1
from sklearn.preprocessing import LabelEncoder

# step-2
le=LabelEncoder()
le

# step-3
visa_df['case_status']=le.fit_transform(visa_df['case_status'])
visa_df['continent']=le.fit_transform(visa_df['continent'])
print(visa_df['case_status'].head(10))
print(visa_df['continent'].head(10))

0             Asia
1             Asia
2             Asia
3             Asia
4           Africa
5             Asia
6             Asia
7    North America
8             Asia
9           Europe
Name: continent, dtype: object
0    1
1    0
2    1
3    1
4    0
5    0
6    0
7    1
8    0
9    0
Name: case_status, dtype: int64
0    1
1    1
2    1
3    1
4    0
5    1
6    1
7    3
8    1
9    2
Name: continent, dtype: int64

In [ ]:
$fit_transform$:                                                       # IMP interview
- fit and transform two different definations
age
1
2
3
4
5
new age: by adding observation with mean value: x+mean
mean=1+2+3+4+5/5=3 =============  this is fit

new age ============== Transform
1+3
2+3
3+3
4+3
5+3

In [96]:
# now we will do inverse transform
print(visa_df['continent'][:5])
le.inverse_transform(visa_df['continent'].head(5))

0    1
1    1
2    1
3    1
4    0
Name: continent, dtype: int64

array(['Asia', 'Asia', 'Asia', 'Asia', 'Africa'], dtype=object)

In [104]:
import pandas as pd                                   # 54 th class
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [99]:
file_path="C:\\DS_Py\\Visadataset.csv"
visa_df=pd.read_csv(file_path)
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

**One hot encoder**

- One hot encoder: at a time only one will be ON(1/True), others are OFF(0/False)
- Suppose case status has two unique lables
- Certified and denied
- in one hot encoder it will create 2 new columns

|case_status| Certified|denied|
|-----------|----------|------|
|certified|1|0|
|denied |0|1|

**Advantage**
  
- one hot encoder new columns are orthogonal each other
- Orthogonality means 90 degrees phase shift
- 90 degree phase shift means perpendicular each other
- perpendicular means independent each other
- Independent means no realtion
- It is very important property that is avoid realtion between variables

**Draw back**

- Assume that you have 100 unique lables for a column
- So it will create 100 new columns
- To process 100 columns we require more ""memory, more time, more hardware""
- This is called **Curse of Dimensionality**

**pd.get_dummies**

In [105]:
file_path="C:\\DS_Py\\Visadataset.csv"
visa_df=pd.read_csv(file_path)

pd.get_dummies(visa_df,columns=['case_status'],dtype='int')

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status_Certified,case_status_Denied
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,0,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,1,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,0,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,0,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,1,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,1,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,1,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,1,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,1,0