**Missing value analysis**

In [31]:
import pandas as pd                                                 # 55 th class
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# np.nan      Recommended
dict1={'Names':['Ram','Sita','Laxman',np.nan],
       'Age':[30,31,np.nan,33],
       'City':[np.nan,'Hyd','Pune','Chennai']}
df=pd.DataFrame(dict1)
df

    Names   Age     City
0     Ram  30.0      NaN
1    Sita  31.0      Hyd
2  Laxman   NaN     Pune
3     NaN  33.0  Chennai

In [4]:
#None= is not recommended
dict1={'Names':['Ram','Sita','Laxman',None],
       'Age':[30,31,None,33],
       'City':[None,'Hyd','Pune','Chennai']}
pd.DataFrame(dict1)

    Names   Age     City
0     Ram  30.0     None
1    Sita  31.0      Hyd
2  Laxman   NaN     Pune
3    None  33.0  Chennai

In [5]:
# Null
dict1={'Names':['Ram','Sita','Laxman','Null'],
       'Age':[30,31,'Null',33],
       'City':['Null','Hyd','Pune','Chennai']}
pd.DataFrame(dict1)

    Names   Age     City
0     Ram    30     Null
1    Sita    31      Hyd
2  Laxman  Null     Pune
3    Null    33  Chennai

$Method-1$:

**Fill with a random number to all Null values**

In [6]:
df.isnull()

   Names    Age   City
0  False  False   True
1  False  False  False
2  False   True  False
3   True  False  False

In [7]:
# it will tell how many missing are there
df.isnull().sum()
df.isna().sum()     # both are same

Names    1
Age      1
City     1
dtype: int64

$fillna$

In [8]:
df.fillna(40,inplace=True) # if you not used ""inplace"" then dataframe will not update
df

    Names   Age     City
0     Ram  30.0       40
1    Sita  31.0      Hyd
2  Laxman  40.0     Pune
3      40  33.0  Chennai

In [9]:
df.dtypes

Names     object
Age      float64
City      object
dtype: object

$Method-2$

**Fill the random value by using column wise**

In [10]:
dict1={'Names':['Ram','Sita','Laxman',np.nan],
       'Age':[30,31,np.nan,33],
       'City':[np.nan,'Hyd','Pune','Chennai']}
df=pd.DataFrame(dict1)
df

    Names   Age     City
0     Ram  30.0      NaN
1    Sita  31.0      Hyd
2  Laxman   NaN     Pune
3     NaN  33.0  Chennai

In [12]:
df['Names'].fillna("Raheem",inplace=True)
df['Age'].fillna(32,inplace=True)           # based on data types fill the values 
df['City'].fillna("Blr",inplace=True)
df

C:\Users\SIDDESH R M\AppData\Local\Temp\ipykernel_21656\3947113278.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(32,inplace=True)           # based on data types fill the values

    Names   Age     City
0     Ram  30.0      Blr
1    Sita  31.0      Hyd
2  Laxman  32.0     Pune
3  Raheem  33.0  Chennai

$Method-3$

- pad
- bfill
- backfill
- ffill

In [13]:
dict1={'Names':['Ram','Sita','Laxman',np.nan],
       'Age':[30,31,np.nan,33],
       'City':[np.nan,'Hyd','Pune','Chennai']}
df=pd.DataFrame(dict1)
df

    Names   Age     City
0     Ram  30.0      NaN
1    Sita  31.0      Hyd
2  Laxman   NaN     Pune
3     NaN  33.0  Chennai

In [21]:
print("======origina=======")
print(df)

print("======pad========")
print(df.fillna(method='pad'))

print("======ffill========")
print(df.fillna(method='ffill'))

print("======bfill========")
print(df.fillna(method='bfill'))

print("======backfill========")
print(df.fillna(method='backfill'))

======origina=======
    Names   Age     City
0     Ram  30.0      NaN
1    Sita  31.0      Hyd
2  Laxman   NaN     Pune
3     NaN  33.0  Chennai
======pad========
    Names   Age     City
0     Ram  30.0      NaN
1    Sita  31.0      Hyd
2  Laxman  31.0     Pune
3  Laxman  33.0  Chennai
======ffill========
    Names   Age     City
0     Ram  30.0      NaN
1    Sita  31.0      Hyd
2  Laxman  31.0     Pune
3  Laxman  33.0  Chennai
======bfill========
    Names   Age     City
0     Ram  30.0      Hyd
1    Sita  31.0      Hyd
2  Laxman  33.0     Pune
3     NaN  33.0  Chennai
======backfill========
    Names   Age     City
0     Ram  30.0      Hyd
1    Sita  31.0      Hyd
2  Laxman  33.0     Pune
3     NaN  33.0  Chennai

C:\Users\SIDDESH R M\AppData\Local\Temp\ipykernel_21656\3312570581.py:5: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  print(df.fillna(method='pad'))
C:\Users\SIDDESH R M\AppData\Local\Temp\ipykernel_21656\3312570581.py:8: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  print(df.fillna(method='ffill'))
C:\Users\SIDDESH R M\AppData\Local\Temp\ipykernel_21656\3312570581.py:11: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  print(df.fillna(method='bfill'))
C:\Users\SIDDESH R M\AppData\Local\Temp\ipykernel_21656\3312570581.py:14: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  print(df.fillna(method='backfill'))

In [25]:
# axis=1
print("======origina=======")
print(df)

print("======pad========")
print(df.fillna(method='pad'))

print("======pad========")
print(df.fillna(method='pad',axis=1))

======origina=======
    Names   Age     City
0     Ram  30.0      NaN
1    Sita  31.0      Hyd
2  Laxman   NaN     Pune
3     NaN  33.0  Chennai
======pad========
    Names   Age     City
0     Ram  30.0      NaN
1    Sita  31.0      Hyd
2  Laxman  31.0     Pune
3  Laxman  33.0  Chennai
======pad========
    Names     Age     City
0     Ram    30.0     30.0
1    Sita    31.0      Hyd
2  Laxman  Laxman     Pune
3     NaN    33.0  Chennai

C:\Users\SIDDESH R M\AppData\Local\Temp\ipykernel_21656\386228566.py:6: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  print(df.fillna(method='pad'))
C:\Users\SIDDESH R M\AppData\Local\Temp\ipykernel_21656\386228566.py:9: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  print(df.fillna(method='pad',axis=1))

$Method-4$:
- Mean
- Median
- Mode

In [27]:
########### read data again #########

dict1={'Names':['Ram','Sita','Laxman',np.nan],
       'Age':[30,31,np.nan,33],
       'City':[np.nan,'Hyd','Pune','Chennai']}
df=pd.DataFrame(dict1)
df

    Names   Age     City
0     Ram  30.0      NaN
1    Sita  31.0      Hyd
2  Laxman   NaN     Pune
3     NaN  33.0  Chennai

In [29]:
mean_age=df['Age'].mean()
df['Age'].fillna(mean_age)

0    30.000000
1    31.000000
2    31.333333
3    33.000000
Name: Age, dtype: float64

In [30]:
median_age=df['Age'].median()
df['Age'].fillna(median_age)

0    30.0
1    31.0
2    31.0
3    33.0
Name: Age, dtype: float64

- mode is used for categorical data
- Mean and median is used for numerical data